<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-A9DN365" name="com.testNgTestCases.TestNgClass2" tests="4" failures="1" timestamp="02 Oct 2021 01:51:33 GMT" time="2.165" errors="0">
  <testcase name="validateGMOonlineLoadedSuccessfully" time="0.048" classname="com.testNgTestCases.TestNgClass2"/>
  <testcase name="ValidateOnLineCatalogLoadedSuccessfully" time="1.724" classname="com.testNgTestCases.TestNgClass2"/>
  <testcase name="ValidatePriceCalculationInPlaceorderPage" time="0.280" classname="com.testNgTestCases.TestNgClass2">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Place Orde] but found [Place Order]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Place Orde] but found [Place Order]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.testNgTestCases.TestNgClass2.ValidatePriceCalculationInPlaceorderPage(TestNgClass2.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidatePriceCalculationInPlaceorderPage -->
  <testcase name="ValidateAllorders" time="0.113" classname="com.testNgTestCases.TestNgClass2"/>
</testsuite> <!-- com.testNgTestCases.TestNgClass2 -->
